### ISSUE TITLE
Add business directory

### ISSUE THREAD

**Issue by shgysk8zer0** [KVSun/kvsun.com#227]
Nobody will tell me what this is, so I'm just creating something.

## Tasks:
- [x] Create table
- [x] Create form
- [x] Handle file uploads
- [x] Create `BusinessDirectory` class in [`\KVSun\KVSAPI`](https://github.com/KVSun/kvsapi)
- [ ] Create `<template>`
- [ ] Handle template in PHP & JavaScript
